name: Build Kernel

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
 
  # Xiaomi
  

  build_renote5_android13:
    name: "Renote 5/Pro"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build_renote5_android13.yml
    secrets: inherit
    
  build_pocox5_android13:
    name: "Poco X5"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build_pocox5_android13.yml
    secrets: inherit
  
  build_pocom3_android13:
    name: "Poco M3"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build_pocom3_android13.yml
    secrets: inherit
  
  build_renote10pro_android13:
    name: "Renote 10 Pro"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build_renote10pro_android13.yml
    secrets: inherit

  build_pocox3_android13:
    name: "Poco X3"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build_pocox3_android13.yml
    secrets: inherit
    
    build_renote8_android13:
    name: "Renote 8"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/build_renote8_android13.yml
    secrets: inherit  
